/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabajopracticon6ejercicio2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanz
 */
public class ListaPrecio extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();

    public ListaPrecio() {
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
        modelo.addColumn("Strock");
        jTtablaPre.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTmaximo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtablaPre = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTminimo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("Entre $");

        jTmaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmaximoActionPerformed(evt);
            }
        });
        jTmaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmaximoKeyReleased(evt);
            }
        });

        jTtablaPre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTtablaPre);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Precios");

        jTminimo.setToolTipText("");
        jTminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTminimoActionPerformed(evt);
            }
        });
        jTminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTminimoKeyReleased(evt);
            }
        });

        jLabel3.setText("Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19)
                                .addComponent(jTminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTmaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTmaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTmaximoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmaximoKeyReleased
        modelo.setRowCount(0);
        filtrarPrecios();

    }//GEN-LAST:event_jTmaximoKeyReleased

    private void jTminimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTminimoKeyReleased
        modelo.setRowCount(0);
        filtrarPrecios();

    }//GEN-LAST:event_jTminimoKeyReleased

    private void jTminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTminimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTminimoActionPerformed

    private void jTmaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmaximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTmaximo;
    private javax.swing.JTextField jTminimo;
    private javax.swing.JTable jTtablaPre;
    // End of variables declaration//GEN-END:variables
private void filtrarPrecios() {
        try {
            Double min = null;
            Double max = null;

            if (!jTminimo.getText().isEmpty()) {
                min = Double.parseDouble(jTminimo.getText());

            }
            if (!jTmaximo.getText().isEmpty()) {
                max = Double.parseDouble(jTmaximo.getText());
            }

            for (Producto pro : Supermercado.getListaProducto()) {
                if (min == null && pro.getPrecio() <= max) {
                    modelo.addRow(new Object[]{
                        pro.getCodigo(),
                        pro.getDescripcion(),
                        pro.getPrecio(),
                        pro.getRubro(),
                        pro.getStock()
                    });
                } else if (min <= pro.getPrecio() && max == null) {
                    modelo.addRow(new Object[]{
                        pro.getCodigo(),
                        pro.getDescripcion(),
                        pro.getPrecio(),
                        pro.getRubro(),
                        pro.getStock()
                    });

                } else if (min <= pro.getPrecio() && pro.getPrecio() <= max) {
                    modelo.addRow(new Object[]{
                        pro.getCodigo(),
                        pro.getDescripcion(),
                        pro.getPrecio(),
                        pro.getRubro(),
                        pro.getStock()
                    });
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite los parametros correctos");
            jTmaximo.setText(null);
        }
    }
}
